# Generated by Django 4.2.20 on 2025-03-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "nombre",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
            ],
        ),
    ]
